#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication_token:
  path: /api/authentication
  methods: ['POST']

blog_index:
  path:       /{_locale}
  controller: App\Controller\BlogController::index
  requirements:
    _locale: '%app_locales%'
  defaults:
    template: base.html.twig
    _locale: '%locale%'


hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix:   /connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
  prefix:   /connect

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
  prefix:   /login

github_login:
  path: /login/check-github