# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    app_locales: en|ru
    factory_locales: ['en_US','ru_RU']

    post_limit_per_page: 5
    post_images_directory: '%kernel.project_dir%/public/uploads/posts'

    user_avatars_directory: '%kernel.project_dir%/public/uploads/avatars'

    url_remember_default_route: 'blog_index'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
            $fakerLocales: '%factory_locales%'
            $postImagesDirectory: '%post_images_directory%'
            $postLimitPerPage: '%post_limit_per_page%'
            $userAvatarsDirectory: '%user_avatars_directory%'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Services\UrlRemember:
        arguments: ['%url_remember_default_route%']
